services:
  web:
    image: httpd:latest
    container_name: apache_server
    ports:
      - "80:80"
    volumes:
      - ./html:/usr/local/apache2/htdocs/
      - ./directory-listing:/usr/local/apache2/htdocs/directory-listing/
      - ./httpd.conf:/usr/local/apache2/conf/httpd.conf
    networks:
      - webnet

networks:
  webnet:
    driver: bridge